### ISSUE TITLE
->new is not exported by the Mojo::IOLoop::ForkCall module

### ISSUE THREAD

**Issue by 0thread** [jberger/Mojo-IOLoop-ForkCall#15]
Installed via CPAN on Debian Stretch, having the code:

```
use Mojo::IOLoop;
use Mojo::IOLoop::ForkCall
my $fc = Mojo::IOLoop::ForkCall->new;
```
results into the following error:

> "Mojo::IOLoop::ForkCall=HASH(0x55f49a250e18)" is not exported by the Mojo::IOLoop::ForkCall module
> Can't continue after import errors at test.pl line 3.
> BEGIN failed--compilation aborted at test.pl line 3.
> 

`

**Comment by jberger** [comment]
You are missing a semi colon on the second line.
